tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "curl"
brew "git"
brew "hashcat"
brew "htop"
brew "iperf3"
brew "mas"
brew "nano"
brew "nmap"
brew "node"
brew "python"
brew "safe-rm"
brew "speedtest-cli"
brew "telnet"
brew "terminal-notifier"
brew "wget"
brew "yarn"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
cask "1password"
cask "alfred"
cask "android-file-transfer"
cask "android-platform-tools"
cask "appcleaner"
cask "balenaetcher"
cask "balsamiq-mockups"
cask "bartender"
cask "cyberduck"
cask "db-browser-for-sqlite"
cask "deluge"
cask "disk-inventory-x"
cask "dropbox"
cask "dropshare"
cask "firefox"
cask "font-awesome-terminal-fonts"
cask "font-firacode-nerd-font"
cask "franz"
cask "google-chrome"
cask "google-drive-file-stream"
cask "insomnia"
cask "intel-power-gadget"
cask "istat-menus"
cask "iterm2"
cask "java"
cask "karabiner-elements"
cask "keka"
cask "kekadefaultapp"
cask "league-of-legends"
cask "macmediakeyforwarder"
cask "micro-snitch"
cask "microsoft-office"
cask "nordvpn"
cask "sdformatter"
cask "snagit"
cask "spotify"
cask "sqlectron"
cask "synology-drive"
cask "timemachineeditor"
cask "tunnelblick"
cask "visual-studio-code"
cask "vlc"
cask "vmware-fusion"
cask "wireshark"
mas "All-in-One Messenger", id: 1456462087
mas "Amphetamine", id: 937984704
mas "AutoMounter", id: 1160435653
mas "Disk Speed Test", id: 425264550
mas "LanScan", id: 472226235
mas "LastPass", id: 926036361
mas "Magnet", id: 441258766
mas "Microsoft Remote Desktop", id: 1295203466
mas "ToothFairy", id: 1191449274
mas "Xcode", id: 497799835
mas "Yoink", id: 457622435
