#!/bin/bash
DATE=`date '+%Y%m%d.%H%M'`
red=`tput setaf 1`
green=`tput setaf 2`
yellow=`tput setaf 3`
reset=`tput sgr0`

# Sets Working Dir as A Script Location
cd "$(dirname ${BASH_SOURCE[0]})"


# checks if mas, terminal-notifier are installed, if not will promt to install
if [ -z $(which mas) ];
then
  brew install mas
fi

if [ -z $(which terminal-notifier) ];
then
  brew install terminal-notifier
fi

# PopUp Notification
terminal-notifier -title "Brewing..." -message "Updates & Clean Ups" -ignoreDnD

# Brew diagnotic
echo "${yellow} Running Brew Diagnotic... ${reset}"
brew doctor 2>&1
brew missing 2>&1
echo -e "${green} Brew Diagnotic Finished. ${reset}" 

# Brew packages update and cleanup
echo "${yellow} Running Brew&Casks Updates... ${reset}" 
brew update 2>&1
brew upgrade 2>&1
brew cask outdated 2>&1
brew cask upgrade 2>&1
brew cleanup -s 2>&1
echo "${green} Finished Brew&Casks Updates ${reset}" 

# App Store Updates
echo "${green} Running AppStore Updates... ${reset}"
mas outdated 2>&1
mas upgrade 2>&1

cd "/Users/${USER}/Projects/brewup"
# Creating Dump FIle
brew bundle dump --force 2>&1

# Pushing to Repo
git add . 2>&1
git commit -m "update_${DATE}" 2>&1
git push 2>&1

echo "${green} Brew File History Can: https://github.com/fire1ce/brewup/commits/master/Brewfile ${reset}"
#echo "chnages can be found here: https://git.io/fpzuF"

# PopUp Notification
terminal-notifier -title "${green} Finished Brewing ${reset}" -message "" -ignoreDnD
echo "${green} All Updates & Cleanups Finnished  ${reset}"
